/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlenderCube: typeof import('./src/components/BlenderCube.vue')['default']
    OutlineDemo: typeof import('./src/components/OutlineDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
  }
}
